version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - cd bookapp
      - chmod +x ./gradlew
      - ./gradlew clean build -x test

artifacts:
  files:
    - bookapp/build/libs/*.jar
    - appspec.yml
    - deploy-scripts/**/*
